# -*- coding: utf-8 -*-
"""ClosedAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aVIYj7t3Q1-u85LWJP9C99ihW1vRjn9A
"""



"""# Task
Build and evaluate a machine learning model using the data from `/content/test.csv` and `/content/reference.csv`, and prepare predictions for submission using the format of `/content/sample_submission.csv`. Summarize the key findings from exploratory data analysis, the chosen model, its performance, and any insights gained.

## Load Data

### Subtask:
Load the available CSV files (`/content/sample_submission.csv`, `/content/test.csv`, `/content/reference.csv`) into pandas DataFrames to inspect their contents and identify the primary dataset for analysis.

**Reasoning**:
First, import the pandas library to handle dataframes. Then, load the three specified CSV files into separate pandas DataFrames, and display the first few rows and column information for each to understand their structure and content.
"""

import pandas as pd

# Load the datasets
sample_submission_df = pd.read_csv('/content/sample_submission.csv')
test_df = pd.read_csv('/content/test.csv')
reference_df = pd.read_csv('/content/reference.csv')

print("--- sample_submission_df ---")
print(sample_submission_df.head())
print(sample_submission_df.info())

print("\n--- test_df ---")
print(test_df.head())
print(test_df.info())

print("\n--- reference_df ---")
print(reference_df.head())
print(reference_df.info())

"""## Exploratory Data Analysis (EDA)

### Subtask:
Perform an initial exploratory data analysis on the main dataset (`reference_df`) to understand its structure, content, and identify potential areas for preprocessing.

**Reasoning**:
To perform an initial exploratory data analysis, I will check for missing values, display descriptive statistics for numerical columns, calculate the length of the 'problem' strings, plot histograms for problem length and the 'answer' column, and check for duplicate 'problem' entries in the `reference_df`.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# 1. Check for missing values
print("--- Missing values in reference_df ---")
print(reference_df.isnull().sum())

# 2. Display descriptive statistics for the 'answer' column
print("\n--- Descriptive statistics for 'answer' column ---")
print(reference_df['answer'].describe())

# 3. Calculate the length of each 'problem' string
reference_df['problem_length'] = reference_df['problem'].apply(len)

# 4. Plot a histogram of the problem_length
plt.figure(figsize=(10, 6))
sns.histplot(reference_df['problem_length'], bins=50, kde=True)
plt.title('Distribution of Problem Lengths')
plt.xlabel('Problem Length')
plt.ylabel('Frequency')
plt.show()

# 5. Plot a histogram of the 'answer' column
plt.figure(figsize=(10, 6))
sns.histplot(reference_df['answer'], bins=50, kde=True)
plt.title('Distribution of Answers')
plt.xlabel('Answer')
plt.ylabel('Frequency')
plt.show()

# 6. Check for any duplicate 'problem' entries
duplicate_problems_count = reference_df['problem'].duplicated().sum()
print(f"\n--- Number of duplicate 'problem' entries: {duplicate_problems_count} ---")

"""## Data Preprocessing

### Subtask:
Clean and preprocess the text data from the 'problem' column in both `reference_df` and `test_df`, and prepare the data for model training by splitting `reference_df` into training and validation sets.

**Reasoning**:
To preprocess the text data and prepare it for model training, I will first convert the 'problem' columns to lowercase in both `reference_df` and `test_df`, then apply TF-IDF vectorization, and finally split the `reference_df` data into training and validation sets as instructed.
"""

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split

# 1. Convert 'problem' column to lowercase and store in 'cleaned_problem'
reference_df['cleaned_problem'] = reference_df['problem'].str.lower()
test_df['cleaned_problem'] = test_df['problem'].str.lower()

# 2. & 3. Instantiate a TfidfVectorizer object
tfidf_vectorizer = TfidfVectorizer()

# 4. Fit the TfidfVectorizer on reference_df and transform into TF-IDF matrix
X_reference_tfidf = tfidf_vectorizer.fit_transform(reference_df['cleaned_problem'])
print(f"Shape of X_reference_tfidf: {X_reference_tfidf.shape}")

# 5. Transform the cleaned_problem column of test_df using the already fitted TfidfVectorizer
X_test_tfidf = tfidf_vectorizer.transform(test_df['cleaned_problem'])
print(f"Shape of X_test_tfidf: {X_test_tfidf.shape}")

# 6. Create the target variable y
y = reference_df['answer']
print(f"Shape of y: {y.shape}")

# 8. Split X_reference_tfidf and y into training and validation sets
X_train, X_val, y_train, y_val = train_test_split(X_reference_tfidf, y, test_size=0.2, random_state=42)

print(f"Shape of X_train: {X_train.shape}")
print(f"Shape of X_val: {X_val.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of y_val: {y_val.shape}")

"""## Model Training

### Subtask:
Select an appropriate machine learning model and train it using the preprocessed training data.

**Reasoning**:
To train a machine learning model, I will import the Ridge regressor, instantiate it, and then fit it to the training data.
"""

from sklearn.linear_model import Ridge

# Instantiate the Ridge model
ridge_model = Ridge()

# Train the model using the training data
ridge_model.fit(X_train, y_train)

print("Ridge model trained successfully.")

"""## Model Fine-tuning

### Subtask:
Optimize the trained model by fine-tuning its hyperparameters.

**Reasoning**:
To fine-tune the Ridge model, I will first define the hyperparameter grid for 'alpha', then use GridSearchCV to perform a systematic search for the best alpha value using cross-validation on the training data, and finally print the best parameters and score.

**Reasoning**:
The previous code failed because `len()` was called on a sparse matrix (`X_train`), which is ambiguous. To correctly specify Leave-One-Out Cross-Validation for `GridSearchCV`, I need to provide the number of samples using `X_train.shape[0]` instead of `len(X_train)`.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Create a scatter plot of actual vs. predicted values
plt.figure(figsize=(8, 6))
sns.scatterplot(x=y_val, y=y_pred_val)

# Add a line for perfect predictions (y=x)
max_val = max(y_val.max(), y_pred_val.max())
min_val = min(y_val.min(), y_pred_val.min())
plt.plot([min_val, max_val], [min_val, max_val], color='red', linestyle='--', label='Perfect Prediction')

plt.title('Actual vs. Predicted Values (Validation Set)')
plt.xlabel('Actual Values')
plt.ylabel('Predicted Values')
plt.legend()
plt.grid(True)
plt.show()

from sklearn.model_selection import GridSearchCV, LeaveOneOut
import numpy as np

# Define the hyperparameter grid for Ridge
# Using np.logspace for a wider range of alpha values
param_grid = {
    'alpha': np.logspace(-3, 2, 10)  # Example: 10 values between 0.001 and 100
}

# Instantiate GridSearchCV
# Given the small dataset, using X_train.shape[0] for Leave-One-Out Cross-Validation (LOOCV)
# For a very small dataset like 8, LOOCV is often preferred for more robust evaluation.
# cv=X_train.shape[0] is equivalent to LeaveOneOut()
grid_search = GridSearchCV(ridge_model, param_grid, cv=X_train.shape[0], scoring='neg_mean_squared_error', n_jobs=-1)

# Fit GridSearchCV to the training data
grid_search.fit(X_train, y_train)

# Print the best parameters and best score
print("Best parameters found: ", grid_search.best_params_)
print("Best cross-validation score (negative MSE): ", grid_search.best_score_)

"""## Model Evaluation and Prediction

### Subtask:
Evaluate the performance of the fine-tuned model on the validation set using appropriate metrics. Use the model to make predictions on the test dataset and prepare the results in the required format.

**Reasoning**:
To evaluate the fine-tuned model, I will first make predictions on the validation set, then calculate the Mean Squared Error (MSE) and R-squared (R2) to assess performance, and finally predict on the test dataset and format the output for submission as instructed.
"""

from sklearn.metrics import mean_squared_error, r2_score

# 1. Make predictions on the validation set
y_pred_val = grid_search.best_estimator_.predict(X_val)

# 2. Calculate and print MSE and R-squared for the validation set
mse_val = mean_squared_error(y_val, y_pred_val)
r2_val = r2_score(y_val, y_pred_val)

print(f"Validation Mean Squared Error: {mse_val}")
print(f"Validation R-squared: {r2_val}")

# 3. Make predictions on the test dataset
test_predictions = grid_search.best_estimator_.predict(X_test_tfidf)

# 4. Create a submission DataFrame
submission_df = pd.DataFrame({
    'id': test_df['id'],
    'answer': test_predictions
})

# Ensure 'answer' column is integer type as per sample_submission_df
submission_df['answer'] = submission_df['answer'].astype(int)

print("\n--- Submission DataFrame Head ---")
print(submission_df.head())
print("\n--- Submission DataFrame Info ---")
print(submission_df.info())

"""## Final Task

### Subtask:
Provide a summary of the EDA findings, the model chosen, its performance, and any insights gained from the analysis and modeling process.

## Summary:

### Data Analysis Key Findings

*   **Data Overview**: Three datasets were loaded: `sample_submission_df` (3 entries), `test_df` (3 entries), and `reference_df` (10 entries). `reference_df` contains problem statements and their corresponding integer answers, while `test_df` contains new problem statements for prediction. All datasets were loaded without missing values.
*   **Exploratory Data Analysis (EDA) for `reference_df`**:
    *   No missing values were found in the `id`, `problem`, or `answer` columns.
    *   The `answer` column has a wide range of values, from 50 to 57447, with a mean of approximately 15474.2 and a standard deviation of 19944.49, indicating significant variability.
    *   No duplicate problem statements were found, suggesting each entry is unique.
*   **Data Preprocessing**:
    *   Problem statements were converted to lowercase.
    *   TF-IDF vectorization was applied to the cleaned 'problem' text, resulting in a feature matrix of shape (10, 290) for `reference_df` and (3, 290) for `test_df`.
    *   `reference_df` was split into training (8 samples) and validation (2 samples) sets.
*   **Model Selection and Tuning**:
    *   A Ridge regression model was selected for training.
    *   Hyperparameter tuning using `GridSearchCV` with Leave-One-Out Cross-Validation (LOOCV) identified an optimal `alpha` value of 100.0.
    *   The best cross-validation score (negative Mean Squared Error) obtained during tuning was -498,349,582.24.
*   **Model Performance**:
    *   On the validation set, the model achieved a Mean Squared Error (MSE) of 265,642,944.95.
    *   The R-squared (R2) score on the validation set was -0.010, indicating that the model performs worse than simply predicting the mean of the target variable for the validation data.

### Insights or Next Steps

*   **Insufficient Data for Robust Modeling**: The very low and negative R-squared score, coupled with a tiny dataset size (10 reference samples, split into 8 for training and 2 for validation), strongly suggests that the model could not learn meaningful patterns. Machine learning models, especially those dealing with text features, typically require much larger datasets for effective training and generalization.
*   **Explore More Sophisticated Text Representations or Models**: Given the poor performance, consider exploring more advanced text embedding techniques (e.g., Word2Vec, GloVe, or BERT embeddings) if more data becomes available, or employing simpler models that are less prone to overfitting on very small datasets. Additionally, collect more training data to improve model robustness and performance.
"""